#!/bin/sh

# Set these paths appropriately

BIN=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/bin
CMD=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/cmd
LIB=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/bulgarian-abbreviations
PARFILE=${LIB}/bulgarian-utf8.par
MWLFILE=${LIB}/bulgarian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
