#!/bin/sh

# Set these paths appropriately

BIN=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/bin
CMD=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/cmd
LIB=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
