#!/bin/sh

# Set these paths appropriately

BIN=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/bin
CMD=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/cmd
LIB=/Users/albertomariopirovano/Documents/Programming/python/notebooks/tis_notebooks/treetagger/macos/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
