#!/bin/sh

# Set these paths appropriately

BIN=/home/francesco/miniconda3/envs/envpy3/bin/trtg/bin
CMD=/home/francesco/miniconda3/envs/envpy3/bin/trtg/cmd
LIB=/home/francesco/miniconda3/envs/envpy3/bin/trtg/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

