#!/bin/sh

# Set these paths appropriately

BIN=/home/francesco/miniconda3/envs/envpy3/bin/trtg/bin
CMD=/home/francesco/miniconda3/envs/envpy3/bin/trtg/cmd
LIB=/home/francesco/miniconda3/envs/envpy3/bin/trtg/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
