#!/bin/sh

# Set these paths appropriately

BIN=/home/francesco/miniconda3/envs/envpy3/bin/trtg/bin
CMD=/home/francesco/miniconda3/envs/envpy3/bin/trtg/cmd
LIB=/home/francesco/miniconda3/envs/envpy3/bin/trtg/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
